const fs = require("fs");
const path = require("path");
const { COMMONS_FILES, commonsUrl } = require("./fetch-place-photos");
const { PLACE_ALBUMS, ROUTE_ALBUMS } = require("./place-albums-config");

let ALBUM_INDEX = {};
try {
  ALBUM_INDEX = require("./place-albums.json");
} catch {
  ALBUM_INDEX = {};
}

function loadAlbumIndex() {
  try {
    return JSON.parse(fs.readFileSync(path.join(__dirname, "place-albums.json"), "utf8"));
  } catch {
    return ALBUM_INDEX;
  }
}

function galleryKeysFor(code) {
  const index = loadAlbumIndex();
  const seen = new Set();
  const keys = [];
  for (const place of ROUTE_ALBUMS[code] || []) {
    const list = (index[place] && index[place].length ? index[place] : PLACE_ALBUMS[place]?.existing) || [];
    for (const key of list) {
      if (key && !seen.has(key)) {
        seen.add(key);
        keys.push(key);
      }
    }
  }
  return keys;
}

const PHOTO = {
  wall1: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1600&q=80",
  wall2: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Badaling_China_Great-Wall-of-China-01.jpg/1280px-Badaling_China_Great-Wall-of-China-01.jpg",
  wall3: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Lakeside_Great_Wall.jpg/1280px-Lakeside_Great_Wall.jpg",
  mutianyu: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Grande_Muraille_de_Chine_Mutianyu_en_2015.jpg/1280px-Grande_Muraille_de_Chine_Mutianyu_en_2015.jpg",
  badaling: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Badaling_China_Great-Wall-of-China-01.jpg/1280px-Badaling_China_Great-Wall-of-China-01.jpg",
  juyong: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Juyongguanfromnorth.jpg/1280px-Juyongguanfromnorth.jpg",
  mutianyuLift: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/CABLE_CAR_TO_THE_GREAT_WALL_BEIJING_CHINA_OCT_2013_%288802166369%29.jpg/1280px-CABLE_CAR_TO_THE_GREAT_WALL_BEIJING_CHINA_OCT_2013_%288802166369%29.jpg",
  gubei: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Gubei_Water_Town_17.jpg/1280px-Gubei_Water_Town_17.jpg",
  gubeiView: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Gubei_water_village_from_Simatai_Great_Wall_in_Beijing_-_panoramio.jpg/1280px-Gubei_water_village_from_Simatai_Great_Wall_in_Beijing_-_panoramio.jpg",
  simatai: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Simatai_section_of_the_Great_Wall.jpg/1280px-Simatai_section_of_the_Great_Wall.jpg",
  panshan: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/%E7%9B%98%E5%B1%B1_-_Mount_Panshan_-_2015.10_-_panoramio.jpg/1280px-%E7%9B%98%E5%B1%B1_-_Mount_Panshan_-_2015.10_-_panoramio.jpg",
  huangyaguan: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Huangyaguan_08_%284921027669%29.jpg/1280px-Huangyaguan_08_%284921027669%29.jpg",
  jinshan: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/20090529_Great_Wall_8185.jpg/1280px-20090529_Great_Wall_8185.jpg",
  mountain1: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1600&q=80",
  mountain2: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=1600&q=80",
  forest: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=80",
  river: "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=1600&q=80",
  lake: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1600&q=80",
  grass: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=80",
  grass2: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
  temple: "https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?auto=format&fit=crop&w=1600&q=80",
  village: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=1600&q=80",
  snow: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1600&q=80",
  sea: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
  canyon: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80",
  mist: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1600&q=80",
  autumn: "https://images.unsplash.com/photo-1476820865390-c52aeebb9891?auto=format&fit=crop&w=1600&q=80",
  night: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?auto=format&fit=crop&w=1600&q=80",
  wutai: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Wutai_shan_Chorten.jpg/1280px-Wutai_shan_Chorten.jpg",
  yungang: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Yungang11_2010.JPG/1280px-Yungang11_2010.JPG",
};

for (const [key, title] of Object.entries(COMMONS_FILES)) {
  if (!PHOTO[key]) PHOTO[key] = commonsUrl(title);
}

const PHOTO_FALLBACK = {
  wall2: ["badaling", "badaling2", "jinshan"],
  wall3: ["huanghua1", "huanghua2", "huanghua3"],
  jinshan: ["jinshan5", "simatai"],
  jinshan5: ["jinshan", "simatai"],
  mutianyu: ["mutianyuLift", "mutianyu2", "mutianyu3"],
  mutianyuLift: ["mutianyu", "mutianyu2"],
  mutianyu2: ["mutianyu", "mutianyu3"],
  badaling: ["badaling2", "juyong", "badaling3"],
  badaling2: ["badaling", "juyong"],
  juyong: ["badaling", "badaling2"],
  gubei: ["gubeiView", "simatai"],
  gubeiView: ["gubei", "simatai"],
  simatai: ["simatai2", "gubeiView", "jinshan"],
  simatai2: ["simatai", "gubei"],
  panshan: ["huangyaguan"],
  huangyaguan: ["panshan"],
  wutai: ["wutaiMount", "xuankong1"],
  wutaiMount: ["wutai", "xuankong1"],
  yungang: ["yungang2", "xuankong1"],
  yungang2: ["yungang", "xuankong2"],
  xuankong1: ["xuankong2", "xuankong3"],
  shangfangCave: [],
  shiduJuma: ["shiduBend", "yesanpo"],
  shiduBend: ["shiduJuma", "yesanpo"],
  lingshan: ["baihuaMeadow", "baihuaSunrise"],
  baihuaMeadow: ["baihuaSunrise", "baihuaTrail", "baihuaGate"],
  fenghuang1: ["fenghuang2"],
  fenghuang2: ["fenghuang1"],
  longqing1: ["longqingBoat", "longqingCable", "longqingView"],
  yanqiDam: ["yanqiPark", "qinglongAerial"],
  yanqiPark: ["yanqiDam", "qinglongAerial"],
  qinglongAerial: ["yanqiDam", "yanqiPark"],
  tianyunGlass: ["tianyunBridge", "shilinxiaUfo"],
  tianyunBridge: ["tianyunGlass", "jingdong"],
  jingdong: ["shilinxiaUfo", "haiziPinggu"],
  shilinxiaUfo: ["jingdong", "tianyunGlass"],
  taoyuan1: ["taoyuan2", "taoyuan3", "taoyuan4"],
  miaofeng: ["miaofengGold", "miaofengView", "miaofengGate"],
  yesanpo: ["shiduJuma", "shiduBend"],
  wulingPeak: ["wulingAutumn", "wulingCable", "wulingView"],
  cuandi1: ["cuandi2", "cuandiPanorama", "shuanglong1"],
  shuanglong1: ["shuanglong2", "shuanglong3"],
  taihang1: ["taihang3", "taihang7", "baishiWall"],
  baishiWall: ["taihang1", "taihang3"],
  chengdeResort: ["chengdePagoda", "chengdeJinshan", "puning"],
  puning: ["putuoZongcheng", "chengdeResort"],
  putuoZongcheng: ["puning", "chengdePagoda"],
  shanhaiguan: ["firstPass", "laolongtou", "laolongtouSea"],
  beidaihe: ["laolongtouSea", "shanhaiguan"],
  saihanba: ["ulanbutong", "fengningMeadow"],
  ulanbutong: ["saihanba", "fengningMeadow"],
  zhangbeiSkyline: ["zhangbeiWheel", "chongliAutumn1"],
  zhangbeiWheel: ["zhangbeiSkyline", "fengningMeadow"],
  chongliAutumn1: ["chongliAutumn2", "chongliAutumn3", "wanlongSki"],
  wanlongSki: ["chongliAutumn1", "chongliAutumn2"],
  miyunRes: ["taoyuan2", "taoyuan1"],
  fengningMeadow: ["ulanbutong", "saihanba"],
};

const MEETUPS = [
  { id: "dzm", name: "东直门东方银座C口", timeHint: "07:30", geo: "地铁2号线东直门站C口" },
  { id: "xzm", name: "西直门凯德mall北门外", timeHint: "07:20", geo: "地铁4号线西直门站" },
  { id: "gm", name: "国贸桥下大巴停靠点", timeHint: "07:10", geo: "地铁1号线国贸站" },
  { id: "lsh", name: "丽泽桥西南角", timeHint: "07:00", geo: "地铁14号线丽泽商务区" },
];

function tiers(list) {
  return list.map(([minPeople, price, memberPrice]) => ({
    minPeople,
    maxPeople: minPeople === 50 ? 55 : undefined,
    price,
    memberPrice,
  }));
}

const day1 = (p199, p179, p159, p139) => tiers([[10, p199, Math.round(p199 * 0.92)], [20, p179, Math.round(p179 * 0.92)], [30, p159, Math.round(p159 * 0.92)], [50, p139, Math.round(p139 * 0.92)]]);
const day2 = () => day1(499, 459, 429, 389);
const day3 = () => day1(899, 829, 769, 699);
const day5 = () => day1(1899, 1699, 1599, 1499);

const ROUTES = [
  {
    code: "R01",
    title: "慕田峪长城缆车一日游",
    subtitle: "万里长城慕田峪独秀 · 缆车/滑道任选",
    days: 1,
    distanceKm: 78,
    difficulty: "休闲",
    category: "长城",
    region: "北京怀柔",
    season: "3-11月",
    tags: ["长城", "亲子", "摄影", "纯玩"],
    coverKey: "mutianyuLift",
    galleryKeys: galleryKeysFor("R01"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30", "bus50"],
    priceTiers: day1(199, 179, 159, 139),
    highlights: [
      "怀柔慕田峪明长城，城墙两侧均有垛口，有「慕田峪独秀」之称",
      "可乘缆车直达 14 号敌楼，再沿城墙走到 20 号敌楼最高点",
      "植被覆盖率高，春秋红叶与夏日绿墙层次清楚，比八达岭更适合拍照",
      "可选滑道下山，亲子团节奏更好控",
      "纯玩不含购物店，给足 4-5 小时登城时间",
      "含往返空调车、导览和长城首道门票（缆车/滑道自理）",
    ],
    description:
      "慕田峪长城在北京怀柔区，是明长城保存和修复较完整的段落之一。城墙两侧都有垛口，敌楼间距密，远看呈龙形贴着山脊起伏。与八达岭相比，这里国际游客也多，但空间更疏朗，植被更好，素有「万里长城，慕田峪独秀」的说法。\n\n本线路从东直门或西直门发车，车程约 1.5-2 小时。入园后可步行或乘缆车至 14 号敌楼，再视体力向正关台或 20 号敌楼方向走。行程不进购物店，午餐自理，适合周末一天打卡世界遗产、带亲友和第一次登长城的人。",
    itinerary: [
      { time: "07:30", title: "市区集合出发", detail: "东直门东方银座 C 口签到，导游举北野行队旗。经京承/怀柔方向，车程约 1.5-2 小时。" },
      { time: "09:30", title: "慕田峪长城", detail: "实名入园。建议乘缆车至 14 号敌楼，沿城墙徒步至 20 号敌楼俯瞰怀柔群山；也可走较缓的正关台方向。游览 4-5 小时。" },
      { time: "12:30", title: "山顶或景区午餐", detail: "可自带干粮，或在景区餐厅简餐（自理）。城上风大，注意补水。" },
      { time: "15:30", title: "滑道或缆车下山", detail: "按体力选择滑道或原路缆车，集合清点人数后返京。" },
      { time: "18:00", title: "抵达市区", detail: "沿途可停靠望京/东直门，结束行程。" },
    ],
    feeInclude: "往返旅游车、司机食宿与高速费、持证导游/领队、长城首道门票、旅行社责任险。",
    feeExclude: "缆车/滑道、餐饮、景区内小交通、个人消费、旅游意外险（可代订）。",
    equipment: "运动鞋、防晒帽、手套（城砖较凉）、500ml 以上饮水、充电宝、薄外套。",
    notices: "长城台阶落差大，膝踝不适者请量力；旺季需配合实名预约；恶劣天气可能改期。",
    meetupPoints: MEETUPS.slice(0, 2),
  },
  {
    code: "R02",
    title: "八达岭·居庸关长城精华一日",
    subtitle: "北门锁钥 + 最知名长城段落联游",
    days: 1,
    distanceKm: 70,
    difficulty: "休闲",
    category: "长城",
    region: "北京延庆 / 昌平",
    season: "四季",
    tags: ["长城", "经典", "亲子"],
    coverKey: "juyong",
    galleryKeys: galleryKeysFor("R02"),
    minGroupSize: 15,
    buses: ["bus30", "bus50"],
    priceTiers: day1(189, 169, 149, 129),
    highlights: [
      "居庸关为京北咽喉，关城、云台与南北城墙格局完整",
      "八达岭是国际知名度最高的明长城段落，设施完善",
      "一天串联「关城+城墙」，适合首次来京和外地亲友",
      "讲解侧重明代防务、驿道与「北门锁钥」",
      "不进购物店，两景区均需实名预约",
      "节假日人流大，可按排期对调先后顺序",
    ],
    description:
      "居庸关位于昌平区南口，是太行余脉与军都山之间的峡谷关城，元明以来就是护卫京师的「北门锁钥」。关城内有云台等遗存，南北城墙贴着峡谷两侧爬升，和八达岭那种山脊墙体是两种看长城的方式。\n\n八达岭在延庆，城墙宽、敌楼密、交通和讲解体系最成熟，也是人流最集中的一段。本线路上午走居庸关看关城，下午到八达岭登城墙，适合接待外地亲友和公司团建。不进购物店；旺季请配合实名预约，并预留排队时间。",
    itinerary: [
      { time: "07:20", title: "西直门集合", detail: "车赴昌平居庸关，经京藏方向约 1.2 小时。" },
      { time: "09:00", title: "居庸关长城", detail: "游览关城、云台与南/北城墙，感受峡谷关隘，约 2 小时。" },
      { time: "12:00", title: "午餐后赴八达岭", detail: "延庆八达岭游览北门锁钥、敌楼与城墙步道，约 3 小时。可按体力只走北侧较缓段。" },
      { time: "16:30", title: "返京", detail: "约 18:30 抵达西直门。" },
    ],
    feeInclude: "往返车费、导览、两景区首道门票、责任险。",
    feeExclude: "缆车、餐饮、个人消费。",
    equipment: "舒适步行鞋、防晒、水和零食。",
    notices: "八达岭节假日极度拥挤，建议错峰；两景区均需实名预约。",
    meetupPoints: [MEETUPS[1], MEETUPS[0]],
  },
  {
    code: "R03",
    title: "黄花城水长城徒步一日",
    subtitle: "长城入水 · 箭扣方向的温柔入口",
    days: 1,
    distanceKm: 85,
    difficulty: "进阶",
    category: "长城",
    region: "北京怀柔",
    season: "4-11月",
    tags: ["长城", "徒步", "摄影", "小众"],
    coverKey: "wall3",
    galleryKeys: galleryKeysFor("R03"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(219, 199, 179, 159),
    highlights: [
      "怀柔黄花城，一段明长城延伸入水库，墙影与湖面同框",
      "官方步道往返约 8-10 公里，比箭扣野长城更安全可控",
      "春花、夏湖、秋叶、冬雪四种气质，摄影团常选西段",
      "保留山野感，但仍在开放景区内，不组织翻越未开放段落",
      "纯徒步团，不进购物店",
      "雨雪天城砖湿滑，领队可改为湖区漫步或改期",
    ],
    description:
      "黄花城水长城在怀柔九渡河镇，因一段城墙修入库区、墙基没入水中而得名。湖面把山脊上的边墙衬出来，是京郊少有的「长城+水」同框机位，和慕田峪的密林城墙、司马台的险楼不是同一种风景。\n\n相比箭扣等未完全开发的野长城，黄花城有官方步道和护栏，适合有一定步行能力、又不愿走险段的城市驴友。领队只走开放段落，强调湿滑和落差；春季山花、秋季红叶、夏季湖光各有味道。",
    itinerary: [
      { time: "07:30", title: "东直门出发", detail: "经怀柔城区前往九渡河黄花城，约 2 小时。" },
      { time: "09:45", title: "水长城徒步", detail: "沿官方步道登城，往返约 8-10 公里，含湖畔取景和西段墙体。按队伍速度切段休息。" },
      { time: "13:00", title: "农家简餐", detail: "可选加餐（自理）或自带能量食物，垃圾请带下山。" },
      { time: "16:00", title: "返程", detail: "约 18:30 回到东直门。" },
    ],
    feeInclude: "往返车、领队、门票、责任险。",
    feeExclude: "餐饮、向导小费、意外险。",
    equipment: "登山鞋、双肩包、头灯（备用）、防风衣、足够饮水。",
    notices: "禁止翻越未开放段落；雨雪天城砖湿滑将改期或改为湖区漫步。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R04",
    title: "司马台长城 + 古北水镇一日",
    subtitle: "北国水乡与明代原貌长城同框",
    days: 1,
    distanceKm: 125,
    difficulty: "休闲",
    category: "长城",
    region: "北京密云",
    season: "四季",
    tags: ["长城", "古镇", "夜景", "情侣"],
    coverKey: "gubei",
    galleryKeys: galleryKeysFor("R04"),
    minGroupSize: 12,
    buses: ["coaster10", "bus30", "bus50"],
    priceTiers: day1(268, 248, 228, 198),
    highlights: [
      "密云司马台明长城以险、密、奇、巧、全著称，保留原貌墙体较多",
      "古北水镇依司马台而建，北方少见的水街与长城同框",
      "东线较险、西线较缓，领队按体能选线",
      "可加购季节性夜游司马台，灯火沿山脊铺开",
      "适合情侣、家庭和摄影，水镇内消费偏高建议自带零食",
      "含联票以排期为准，缆车和夜游加场自理",
    ],
    description:
      "司马台长城在密云古北口一带，敌楼密度高、墙体陡、保留了较多明代原貌，和完全修复的八达岭观感不同。东线更险，西线相对可走，常与古北水镇做成一日组合。\n\n古北水镇紧贴司马台山脚，以水街、石桥和北方面的夜灯为卖点，从城墙回头能拍到水镇全景。本线路上午登城、下午走镇；若报名夜游场次，返京会延后到 21:30 以后，请看排期备注。",
    itinerary: [
      { time: "07:00", title: "国贸/东直门发车", detail: "京承高速赴密云古北口，约 2-2.5 小时。" },
      { time: "10:00", title: "司马台长城", detail: "东线较险，西线较缓，领队按团队体能选择。可乘缆车减负。" },
      { time: "13:30", title: "古北水镇", detail: "漫步水街、石桥和长城背景机位，自由用餐（自理）。" },
      { time: "17:30", title: "返京", detail: "常规团约傍晚发车；夜游团约 21:30 后返城。" },
    ],
    feeInclude: "车费、导览、水镇+司马台联票（以排期为准）、责任险。",
    feeExclude: "缆车、夜游加场、餐饮住宿、温泉。",
    equipment: "舒适鞋、防晒、相机、夜游需加厚外套。",
    notices: "水镇内消费偏高，建议自带零食；夜游名额有限需提前锁定排期。",
    meetupPoints: [MEETUPS[2], MEETUPS[0]],
  },
  {
    code: "R05",
    title: "十渡拒马河漂流一日",
    subtitle: "京西小桂林 · 喀斯特河谷玩水",
    days: 1,
    distanceKm: 100,
    difficulty: "休闲",
    category: "玩水",
    region: "北京房山",
    season: "6-9月",
    tags: ["漂流", "亲子", "避暑", "团建"],
    coverKey: "shiduJuma",
    galleryKeys: galleryKeysFor("R05"),
    minGroupSize: 15,
    buses: ["bus30", "bus50"],
    priceTiers: day1(219, 199, 179, 149),
    highlights: [
      "房山十渡因拒马河十次转弯得名，喀斯特峰林有「京西小桂林」之称",
      "夏季以拒马河漂流为主，两岸峰丛随船展开",
      "春秋可改东湖港、玻璃栈道或河谷徒步，后台按季节切项目包",
      "团建氛围好，可加蹦极、栈道等自费项目",
      "纯玩不进购物店，不会游泳也可漂但必须穿救生衣",
      "雷雨天停漂，儿童需家长陪同",
    ],
    description:
      "十渡在房山区拒马河谷，河水在峰林间反复拐弯，渡口因此得名。沿岸是北方少见的喀斯特峰丛与河滩，和阳朔漓江不是同一套地貌，但远看确实有「水绕山转」的感觉，所以常被叫作京西小桂林。\n\n夏季线路核心是漂流，约 1.5-2 小时，岸边峰林一直跟着走。春秋水凉则改为观光、玻璃栈道或轻徒步。属于房山世界地质公园大范围内的经典玩水点，和河北野三坡隔河相望，两日线常把两岸连起来。",
    itinerary: [
      { time: "07:00", title: "丽泽/西直门出发", detail: "京石方向经房山，约 2 小时到十渡镇。" },
      { time: "09:30", title: "拒马河漂流或河谷观光", detail: "夏季漂流约 1.5-2 小时，必须穿救生衣；非漂流季改为东湖港/峰林步道。" },
      { time: "12:30", title: "午餐+自由项目", detail: "玻璃栈道、乐园项目自理。可在河边短暂停留拍照。" },
      { time: "16:00", title: "返京", detail: "约 18:30 到丽泽。" },
    ],
    feeInclude: "车费、领队、漂流或景区首道票（见排期）、责任险。",
    feeExclude: "午餐、自费项目、换洗衣物租赁。",
    equipment: "速干衣、拖鞋+运动鞋、防晒、防水袋、换洗衣物。",
    notices: "不会游泳也可漂流但需穿救生衣；雷雨天停止漂流；儿童需家长陪同。",
    meetupPoints: [MEETUPS[3], MEETUPS[1]],
  },
  {
    code: "R06",
    title: "灵山高山草甸一日",
    subtitle: "北京最高峰 2303 米 · 夏季清凉",
    days: 1,
    distanceKm: 120,
    difficulty: "进阶",
    category: "登山",
    region: "北京门头沟",
    season: "6-10月",
    tags: ["登山", "草甸", "避暑", "摄影"],
    coverKey: "lingshan",
    galleryKeys: galleryKeysFor("R06"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(239, 219, 199, 179),
    highlights: [
      "东灵山主峰海拔 2303 米，是北京市最高点，有「京西珠穆朗玛」之称",
      "山体跨北京门头沟与河北界，盛夏草甸和气温明显低于城区",
      "7-8 月野花最盛，10 月可见初雪点缀",
      "可乘景区交通减负，也可全程徒步，强度高于普通一日游",
      "山顶温差大，需保暖层；心脏病、高血压患者不宜强登",
      "垃圾必须带下山，勿偏离标识步道",
    ],
    description:
      "东灵山在门头沟清水镇与河北涿鹿交界，主峰 2303 米，是北京境内海拔最高的山。山顶一带是亚高山草甸，盛夏仍凉爽，远看有高原的开阔感，和城区香山、凤凰岭完全不是一个量级。\n\n本线路车程约 2.5-3 小时，途经斋堂。7-8 月草甸最盛，10 月可能见初雪。报名需确认膝盖和心肺；领队会按天气决定步行还是小交通。不挑战未开放野路。",
    itinerary: [
      { time: "06:30", title: "西直门早发", detail: "车程约 2.5-3 小时，途经斋堂、清水，山区弯道请备晕车药。" },
      { time: "09:30", title: "登山或景区交通", detail: "视天气选择步行或小交通至草甸区，再视体力接近主峰方向。" },
      { time: "13:00", title: "草甸午餐", detail: "自带能量食物，注意垃圾带下山，风大时注意保暖。" },
      { time: "15:30", title: "下山返程", detail: "约 19:30 抵京，归来较晚。" },
    ],
    feeInclude: "车费、领队、门票、责任险。",
    feeExclude: "景区小交通、餐饮、氧气瓶等。",
    equipment: "登山鞋、冲锋衣、防晒、头巾、至少 1.5L 水、高热量零食。",
    notices: "山顶温差大请备保暖层；心脏病、高血压患者不宜；勿偏离标识步道。",
    meetupPoints: [MEETUPS[1]],
  },
  {
    code: "R07",
    title: "百花山森林公园一日",
    subtitle: "京西天然氧吧 · 亚高山草甸与原始林",
    days: 1,
    distanceKm: 110,
    difficulty: "进阶",
    category: "登山",
    region: "北京门头沟",
    season: "5-10月",
    tags: ["森林", "徒步", "避暑", "观花"],
    coverKey: "baihuaMeadow",
    galleryKeys: galleryKeysFor("R07"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(229, 209, 189, 169),
    highlights: [
      "百花山主峰约 1991 米，在门头沟清水镇与房山史家营交界",
      "亚高山草甸加原始次生林，盛夏仍是京西天然氧吧",
      "黄花、绣线菊等花期可遇，步道成熟适合进阶入门",
      "天气好时可看白草畔方向云海",
      "只走景区标识步道，不挑战野路",
      "山区信号弱，请全程跟随领队，勿采摘野生植物",
    ],
    description:
      "百花山在北京西南部，主峰海拔约 1991 米，山北是门头沟清水镇，山南是房山史家营。森林覆盖率高，顶部有亚高山草甸，和东灵山同属京西高海拔徒步圈，但步道更成熟、距离稍短。\n\n线路以景区步道为主，往返大约 10-14 公里，强调能走完、能看花、能安全下山。花期看山花，盛夏避暑，秋季看草甸变色。可与白草畔做成两日或三日组合，本一日线不赶场。",
    itinerary: [
      { time: "06:40", title: "西直门出发", detail: "约 2.5 小时抵达百花山北门一带。" },
      { time: "09:30", title: "森林与草甸徒步", detail: "往返 10-14 公里，按队伍速度切段，主走标识步道。" },
      { time: "16:00", title: "返京", detail: "约 19:00 到西直门。" },
    ],
    feeInclude: "车费、领队、门票、责任险。",
    feeExclude: "缆车、餐食。",
    equipment: "登山鞋、防风衣、手套、垃圾袋、头灯。",
    notices: "山区信号弱，全程跟随领队；请勿采摘野生植物。",
    meetupPoints: [MEETUPS[1], MEETUPS[3]],
  },
  {
    code: "R08",
    title: "凤凰岭·阳台山穿越一日",
    subtitle: "城西经典穿越 · 半天能走完的山野",
    days: 1,
    distanceKm: 45,
    difficulty: "进阶",
    category: "登山",
    region: "北京海淀",
    season: "3-11月",
    tags: ["穿越", "徒步", "近郊", "周末"],
    coverKey: "fenghuang1",
    galleryKeys: galleryKeysFor("R08"),
    minGroupSize: 8,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(159, 139, 119, 99),
    highlights: [
      "海淀凤凰岭古称千峰山，有「京西小黄山」之称，车程约 1 小时",
      "景区内有龙泉寺、桃源观、飞来石和天梯等自然人文点",
      "进阶团可走凤凰岭上、阳台山下的经典近郊穿越",
      "休闲团改为单景区环线，秋季红叶、夏季沟谷都好看",
      "出城即达，适合不想太早起的周末徒步",
      "穿越须听从领队，禁止独自抄近路，夏季防雷雨",
    ],
    description:
      "凤凰岭在海淀西北部，古称千峰山，因摩崖「凤凰岭」得名，民间有「京西小黄山」的说法。传说铁拐李曾在此修仙，景区内龙泉寺、桃源观、飞来石、天梯把山野和寺庙叠在一起，是城里通勤族最常走的近郊山之一。\n\n强度可调：休闲团走景区环线看天梯和寺院；进阶团完成凤凰岭—阳台山穿越，从另一侧出山接车。车程短、收工早，纯 AA 氛围，车型随人数升级。",
    itinerary: [
      { time: "07:30", title: "西直门或东直门", detail: "约 1 小时到凤凰岭景区门口。" },
      { time: "09:00", title: "穿越或环线", detail: "领队根据天气和队员构成决定：环线看龙泉寺/天梯，或岭-山穿越至阳台山。" },
      { time: "15:30", title: "出山接车", detail: "穿越团在阳台山侧上车，环线团原路出；约 17:30 到市区。" },
    ],
    feeInclude: "包车、领队、责任险。",
    feeExclude: "两景区门票（部分时段免票政策以现场为准）、餐食。",
    equipment: "登山鞋、护膝、2L 水、雨衣。",
    notices: "穿越需听从领队，禁止独自抄近路；夏季防雷雨。",
    meetupPoints: [MEETUPS[1], MEETUPS[0]],
  },
  {
    code: "R09",
    title: "延庆龙庆峡一日游",
    subtitle: "小三峡 · 游船看峡谷",
    days: 1,
    distanceKm: 90,
    difficulty: "休闲",
    category: "山水",
    region: "北京延庆",
    season: "4-10月",
    tags: ["游船", "亲子", "峡谷", "休闲"],
    coverKey: "longqing1",
    galleryKeys: galleryKeysFor("R09"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day1(199, 179, 159, 139),
    highlights: [
      "延庆龙庆峡又称古城水库，峡谷被叫作「小三峡」",
      "夏季乘船进峡，体力要求低，适合老人小孩",
      "岸边有步道和索道，峡谷风大请备外套",
      "冬季可改为冰灯夜游（季节活动，返京较晚）",
      "可顺路看延庆城区或海坨山远景",
      "游船班次受水位和天气影响，以现场为准",
    ],
    description:
      "龙庆峡在延庆旧县镇，水库也称古城水库，峡谷两岸壁立，乘船进去后有「小三峡」的观感。它不是长江三峡的缩小版，而是燕山里一段被水填满的石灰岩峡谷，夏天游船、冬天冰灯，是延庆最经典的亲水一日。\n\n本线路把体力门槛放低：上船看峡，再走一段岸边栈道。适合带老人小孩的家庭团和不愿登山的公司团。后台可按排期把夏季游船换成冬季冰灯，冰灯季会夜间返京。",
    itinerary: [
      { time: "07:30", title: "西直门出发", detail: "经京藏赴延庆旧县，约 1.5-2 小时。" },
      { time: "10:00", title: "龙庆峡游船与步道", detail: "乘船观峡谷，再走岸边栈道；可选索道（自理）。午餐在景区或延庆城区。" },
      { time: "15:30", title: "返京", detail: "可在延庆城区短暂停留；冰灯季夜间返城。" },
    ],
    feeInclude: "车费、导游、门票+游船（以排期为准）、责任险。",
    feeExclude: "餐饮、索道、二次门票。",
    equipment: "防滑鞋、外套（峡谷风大）、防晒。",
    notices: "游船班次受水位和天气影响；冰灯季夜间返京较晚。",
    meetupPoints: [MEETUPS[1], MEETUPS[0]],
  },
  {
    code: "R10",
    title: "平谷天云山玻璃栈道一日",
    subtitle: "北方张家界气质 · 峰林与高空栈道",
    days: 1,
    distanceKm: 95,
    difficulty: "休闲",
    category: "山水",
    region: "北京平谷",
    season: "4-11月",
    tags: ["玻璃栈道", "峰林", "亲子", "网红"],
    coverKey: "tianyunGlass",
    galleryKeys: galleryKeysFor("R10"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day1(189, 169, 149, 129),
    highlights: [
      "平谷天云山以石英砂岩峰林和玻璃栈道闻名，远看有张家界式的柱状山体",
      "高空玻璃平台、玻璃桥是核心体验，有护栏但仍恐高",
      "同属京东平谷山系，可与石林峡、京东大峡谷对照着看",
      "游览时间留足约 4 小时，避免下车拍一张就走",
      "大风和雷雨会关闭栈道，恐高请提前告知领队",
      "平谷水果季可加农园（季节，自理）",
    ],
    description:
      "天云山在北京平谷，山体是京东一带少见的峰林、残丘，景区以玻璃栈道和高空观景台出名。它不是湘西张家界，但柱状山体和云雾天气下的轮廓，确实会让人联想到那种「山从地上戳出来」的感觉。\n\n我们把游览时间留到约 4 小时：走栈道、上观景台、再走一段峰林步道。图库中的玻璃平台、玻璃桥即本景区实拍；同区石林峡 UFO 平台、京东大峡谷可作为地貌对照。恐高者可绕行高空段。",
    itinerary: [
      { time: "07:30", title: "东直门出发", detail: "约 1.5-2 小时抵达平谷天云山。" },
      { time: "10:00", title: "天云山景区", detail: "玻璃栈道、观景台、峰林步道，约 4 小时。大风停栈道时改为步道观光。" },
      { time: "16:00", title: "返京", detail: "约 18:00 到东直门。" },
    ],
    feeInclude: "车费、领队、门票、责任险。",
    feeExclude: "玻璃栈道加项（若未含）、餐食。",
    equipment: "防滑鞋、恐高者可备眼罩、防晒。",
    notices: "大风和雷雨会关闭栈道；恐高请提前告知领队。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R11",
    title: "房山上方山云水洞一日",
    subtitle: "九洞十二峰 · 溶洞+山寺",
    days: 1,
    distanceKm: 75,
    difficulty: "休闲",
    category: "文化",
    region: "北京房山",
    season: "3-11月",
    tags: ["溶洞", "古寺", "亲子", "地质"],
    coverKey: "shangfangCave",
    galleryKeys: galleryKeysFor("R11"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(179, 159, 139, 119),
    highlights: [
      "房山上方山国家森林公园，云水洞为华北著名石灰岩溶洞",
      "洞内钟乳石、石笋发育，有「云水奇洞」之称，洞内恒温请加衣",
      "山上寺院观林立，明清有「南有九华、北有上方」之说，兜率寺等为主要香火点",
      "同属房山世界地质公园，溶洞、山林、寺庙一天能看完",
      "强度低于纯登山线，适合对地质和历史文化感兴趣的家庭",
      "溶洞地面潮湿，寺院内请勿喧哗，尊崇礼仪",
    ],
    description:
      "上方山在房山韩村河一带，是北京西南部的国家森林公园，也是房山世界地质公园的组成部分。云水洞是华北知名的喀斯特溶洞，洞体深、景观层多，钟乳石和石幔在灯光下像被水「冻」住的云，所以叫云水洞。洞内常年凉，和洞外山温差明显，必须备薄外套。\n\n山上寺观沿山分布，历史上香火与九华山南北并称，有「南有九华、北有上方」的说法。本线路上午进洞看地质，下午量力走林道和寺院，不强制登顶。封面即维基共享中的上方山云水洞实拍，不再误用故宫太和殿照片。",
    itinerary: [
      { time: "07:30", title: "丽泽出发", detail: "京石方向约 1.5 小时到上方山。" },
      { time: "09:30", title: "云水洞", detail: "跟随讲解看溶洞主体厅堂与石景，洞内潮湿恒温，请穿防滑鞋、备外套。" },
      { time: "12:30", title: "山间寺院与林道", detail: "量力走上方山寺观和林道，不强制登顶。午餐自理。" },
      { time: "16:00", title: "返京", detail: "约 18:00 前后到丽泽或西直门。" },
    ],
    feeInclude: "车费、讲解、门票、责任险。",
    feeExclude: "索道、香火功德、餐食。",
    equipment: "洞内加衣、防滑鞋、手电备用。",
    notices: "溶洞地面潮湿；尊崇寺院礼仪，请勿喧哗。",
    meetupPoints: [MEETUPS[3], MEETUPS[1]],
  },
  {
    code: "R12",
    title: "怀柔青龙峡 + 雁栖湖一日",
    subtitle: "峡谷瀑布与雁栖湖国际会都风光",
    days: 1,
    distanceKm: 80,
    difficulty: "休闲",
    category: "山水",
    region: "北京怀柔",
    season: "4-10月",
    tags: ["瀑布", "湖泊", "亲子", "团建"],
    coverKey: "yanqiDam",
    galleryKeys: galleryKeysFor("R12"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day1(199, 179, 159, 139),
    highlights: [
      "怀柔青龙峡为峡谷水库景区，可从烽火台一带俯瞰龙峡湖",
      "夏季峡谷水量大时瀑布更明显，可选滑道（自理）",
      "雁栖湖即北台上水库，水面开阔，是 APEC 雁栖湖国际会都所在",
      "下午环湖步道或骑行，适合团建收尾",
      "行程一张一弛：上午峡谷，下午湖岸",
      "汛期关注峡谷安全提示，湖区只在指定区域活动",
    ],
    description:
      "青龙峡在怀柔，是一段被水填满的山峡，从山上烽火台可以鸟瞰龙峡湖，和单纯的湖滨公园不是一种尺度。夏季雨后瀑布更明显，体力要求中等，可选滑道。\n\n雁栖湖本名北台上水库，拦截雁栖河，1959-1962 年建成，后来因国际会议和环湖景观被更多人知道。本线路上午走青龙峡，下午到雁栖湖南坝和公园岸线散步或骑行，适合公司团建和家庭。可按客户把下午改成环湖骑行或湖心岛（以开放为准）。",
    itinerary: [
      { time: "07:30", title: "东直门出发", detail: "先赴怀柔青龙峡，约 1.5 小时。" },
      { time: "09:30", title: "青龙峡", detail: "峡谷、湖面、可选滑道。从高处可看龙峡湖全景。" },
      { time: "13:30", title: "雁栖湖", detail: "南坝、环湖步道或骑行，拍照留念。午餐自理。" },
      { time: "16:30", title: "返京", detail: "约 18:00 到东直门。" },
    ],
    feeInclude: "车费、导游、两景区门票（骑行租赁视排期）、责任险。",
    feeExclude: "滑道、餐饮、游船加项。",
    equipment: "运动鞋、防晒、水。",
    notices: "汛期关注峡谷安全提示；湖区请在指定区域活动。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R13",
    title: "密云黑龙潭 + 桃源仙谷一日",
    subtitle: "潭瀑连珠 · 京郊清凉谷地",
    days: 1,
    distanceKm: 100,
    difficulty: "休闲",
    category: "山水",
    region: "北京密云",
    season: "5-10月",
    tags: ["瀑布", "避暑", "徒步", "亲子"],
    coverKey: "taoyuan1",
    galleryKeys: galleryKeysFor("R13"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day1(209, 189, 169, 149),
    highlights: [
      "密云桃源仙谷植被好、步道友好，可远眺密云水库",
      "黑龙潭以潭瀑连珠著称，夏季亲水，石阶湿滑",
      "两个谷地都在密云东北，是北京盛夏的「空调房」",
      "适合不想太累又想进山的家庭和轻度徒步者",
      "禁止在未开放水域游泳，雨后取消近水项目",
      "下午早点返城，避开周日晚高峰尾部",
    ],
    description:
      "密云东北部的谷地比城区低好几度。黑龙潭沿沟叠着一串潭和瀑，夏天最能亲水，台阶湿滑，要穿防滑鞋。桃源仙谷更偏林道和山景，南山回路一带可以远看密云水库，步道比潭区友好，适合饭后消食。\n\n本线路把两个经典谷串起来：上午黑龙潭走水，下午桃源仙谷轻松走。图库以桃源仙谷实拍为主（含远眺密云水库、谷中彩虹等公开影像）；黑龙潭以现场体验为主。中午山间用餐，下午较早返城。",
    itinerary: [
      { time: "07:20", title: "东直门出发", detail: "京密路或京承高速，约 2 小时进入密云东部谷地。" },
      { time: "09:30", title: "黑龙潭", detail: "沿潭拾级，注意湿滑，不开放水域禁止下水。" },
      { time: "13:30", title: "桃源仙谷", detail: "林道与观景台，可远眺密云水库方向，轻松步道。" },
      { time: "16:00", title: "返京", detail: "约 18:00-18:30 到东直门。" },
    ],
    feeInclude: "车费、门票、领队、责任险。",
    feeExclude: "餐食、索道。" ,
    equipment: "溯溪鞋或防滑鞋、速干袜、毛巾。",
    notices: "禁止在未开放水域游泳；雨后取消近水项目。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R14",
    title: "京东大峡谷 + 石林峡一日",
    subtitle: "平谷双峡 · 一线天与石林",
    days: 1,
    distanceKm: 90,
    difficulty: "休闲",
    category: "山水",
    region: "北京平谷",
    season: "4-11月",
    tags: ["峡谷", "亲子", "摄影"],
    coverKey: "jingdong",
    galleryKeys: galleryKeysFor("R14"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day1(199, 179, 159, 139),
    highlights: [
      "京东大峡谷在平谷鱼子山一带，一线天、飞瀑和峡谷步道是核心",
      "石林峡以石林造型和高空观景平台（含 UFO 平台）出名",
      "同属平谷东线，一天两个景区，上午费体力、下午偏观光",
      "东线出城相对顺畅，适合摄影和家庭",
      "部分高空项目恐高者可绕行",
      "玻璃台等加项以现场开放为准",
    ],
    description:
      "京东大峡谷在平谷东部鱼子山，沟谷深、有一线天和飞瀑，是京东开发较早的峡谷景区。石林峡更偏石柱、石林和高空平台，有玻璃台和飞碟外形的观景设施，和天云山同属平谷峰林观光带，但不是同一个园。\n\n我们把体力放在上午大峡谷，下午石林峡以观光和拍照为主。图库均为平谷境内实拍：大峡谷、石林峡平台、天云山玻璃桥可对照峰林气质。",
    itinerary: [
      { time: "07:30", title: "东直门出发", detail: "约 1.5-2 小时到平谷鱼子山。" },
      { time: "09:30", title: "京东大峡谷", detail: "峡谷步道、一线天与观瀑，注意湿滑。" },
      { time: "13:30", title: "石林峡", detail: "石林、UFO/玻璃台等视开放情况，恐高可绕行。" },
      { time: "16:30", title: "返京", detail: "约 18:30 到东直门。" },
    ],
    feeInclude: "车费、双门票、领队、责任险。",
    feeExclude: "玻璃台等加项、餐食。",
    equipment: "运动鞋、防晒、雨衣。",
    notices: "部分高空项目恐高者可绕行。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R15",
    title: "妙峰山香道 + 涧沟玫瑰一日",
    subtitle: "进香古道 · 五月玫瑰沟",
    days: 1,
    distanceKm: 55,
    difficulty: "进阶",
    category: "文化",
    region: "北京门头沟",
    season: "4-10月",
    tags: ["古道", "文化", "徒步", "花海"],
    coverKey: "miaofengGold",
    galleryKeys: galleryKeysFor("R15"),
    minGroupSize: 8,
    buses: ["coaster10", "bus30"],
    priceTiers: day1(169, 149, 129, 109),
    highlights: [
      "门头沟妙峰山是华北著名进香道，金顶娘娘庙民俗氛围浓",
      "传统香会、茶棚文化可讲，香期人多听从现场管理",
      "涧沟玫瑰谷约 5 月花期极盛，非花期以香道和金顶为主",
      "近郊车程约 1.2 小时，收工早",
      "可乘景区交通减负，花粉过敏者花期请谨慎",
      "把京西民俗和自然徒步合在一条一日线上",
    ],
    description:
      "妙峰山在门头沟，金顶一带是华北知名的民间进香地，香道、茶棚、香会把山路走成了民俗现场，而不只是一座普通郊野公园。山顶娘娘庙和金顶门楼是传统朝顶点，俯瞰可见西山层叠。\n\n涧沟村的玫瑰种植使五月成为花期窗口；非花期则主走香道和金顶。本线路近郊、收工早，适合对京西民俗感兴趣、又不想走太远的周末。",
    itinerary: [
      { time: "07:40", title: "西直门出发", detail: "约 1.2 小时到妙峰山/涧沟方向。" },
      { time: "09:00", title: "香道与金顶", detail: "量力徒步香道，可乘景区交通减负。金顶看娘娘庙与门楼。" },
      { time: "13:30", title: "涧沟村", detail: "花期看玫瑰沟，平时喝茶休息。午餐自理。" },
      { time: "16:00", title: "返京", detail: "约 17:30-18:00 到西直门。" },
    ],
    feeInclude: "车费、领队、门票、责任险。",
    feeExclude: "小交通、农家餐。",
    equipment: "登山鞋、花期防晒、花粉过敏者请谨慎。",
    notices: "香会期间人多，听从现场管理。",
    meetupPoints: [MEETUPS[1]],
  },
  {
    code: "R16",
    title: "慕田峪 + 古北水镇夜司马台",
    subtitle: "昼夜双长城 · 住进水镇",
    days: 2,
    distanceKm: 130,
    difficulty: "休闲",
    category: "长城",
    region: "北京怀柔 / 密云",
    season: "4-11月",
    tags: ["两日游", "夜长城", "古镇", "情侣"],
    coverKey: "simatai",
    galleryKeys: galleryKeysFor("R16"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30", "bus50"],
    priceTiers: day2(),
    highlights: [
      "第一天慕田峪从容登城，感受修复完整的「独秀」段落",
      "入住古北水镇，不用赶末班车看夜景",
      "夜游司马台，灯火沿原貌城墙铺开，和白天慕田峪气质完全不同",
      "第二天早起拍水镇晨雾和长城背景再返京",
      "含双早与一晚住宿（双人一间），纯玩无购物",
      "夜游若因天气取消，改为水镇夜景；单人补房差",
    ],
    description:
      "这是北京周边最经典的 2 日小长线：把怀柔慕田峪和密云司马台/古北水镇拆成昼夜两场。慕田峪城墙完整、植被好，适合白天慢慢走；司马台更险、更原貌，夜间点灯后山脊像一条亮线，和白天完全不是一种照片。\n\n第一天下午转入水镇入住，晚上夜游司马台；第二天早起走桥巷、拍长城背景，下午返京。适合情侣、家庭和接待亲友。报价以 2 人一间为基础。",
    itinerary: [
      { time: "D1 07:30", title: "赴慕田峪", detail: "缆车登城，下午转场密云古北水镇入住。" },
      { time: "D1 18:30", title: "夜游司马台", detail: "灯光长城，注意保暖；取消则改为水镇夜景。" },
      { time: "D2 08:00", title: "水镇慢游", detail: "桥巷、早餐、从镇内或城上看水镇与司马台同框。" },
      { time: "D2 14:00", title: "返京", detail: "约 16:30 到东直门。" },
    ],
    feeInclude: "往返车、导览、门票（含水镇/司马台/慕田峪，以排期套餐为准）、1 晚双人房、双早、责任险。",
    feeExclude: "缆车、单人房差、午餐晚餐、温泉。",
    equipment: "两日替换衣物、夜游羽绒服或厚外套、舒适鞋。",
    notices: "报价以 2 人一间为基础；单人需补房差。夜游若因天气取消将改为水镇夜景。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R17",
    title: "十渡 + 野三坡百里峡",
    subtitle: "拒马河两岸 · 京冀经典周末",
    days: 2,
    distanceKm: 140,
    difficulty: "休闲",
    category: "山水",
    region: "北京房山 / 河北涞水",
    season: "4-10月",
    tags: ["两日游", "峡谷", "漂流", "团建"],
    coverKey: "yesanpo",
    galleryKeys: galleryKeysFor("R17"),
    minGroupSize: 15,
    buses: ["bus30", "bus50"],
    priceTiers: day2(),
    highlights: [
      "河北涞水野三坡百里峡有「天下第一峡」之称，蝎子沟是核心段",
      "与房山十渡分列拒马河两岸，同属喀斯特河谷",
      "D1 走峡，D2 十渡玩水或玻璃栈道，住宿山间不赶早高峰出城",
      "夏季偏漂流，春秋偏峡谷徒步和摄影",
      "非常适合公司团建；河北景区请带身份证原件",
      "可选《印象野三坡》等演出（自理、季节性）",
    ],
    description:
      "野三坡在河北涞水，百里峡把拒马河支脉切成深沟，蝎子沟一段最常走，岩壁近、谷底有水，被叫作「天下第一峡」更多是景观口碑，而不是官方唯一命名。河对岸就是北京房山十渡，地质上同属华北喀斯特，行政上一个河北、一个北京。\n\n两日线 D1 走百里峡、住野三坡或十渡，D2 回十渡漂流或东湖港再返京。夏季偏水，春秋偏峡。请带身份证，两边预约政策可能不同。",
    itinerary: [
      { time: "D1 07:00", title: "赴百里峡", detail: "蝎子沟核心段徒步观光，傍晚入住野三坡或十渡酒店。" },
      { time: "D1 19:00", title: "可选演出", detail: "《印象野三坡》等（自理/季节）。" },
      { time: "D2 08:30", title: "十渡拒马河", detail: "漂流或东湖港峰林，下午返京。" },
    ],
    feeInclude: "车费、住宿 1 晚、部分门票、领队、责任险。",
    feeExclude: "漂流加项（若未含）、演出、餐（含早）。",
    equipment: "换洗衣物、速干、拖鞋、充电器。",
    notices: "河北景区预约政策可能与北京不同，请带身份证原件。",
    meetupPoints: [MEETUPS[3], MEETUPS[1]],
  },
  {
    code: "R18",
    title: "雾灵山避暑 + 雾灵湖",
    subtitle: "华北凉岛 · 三里不同天",
    days: 2,
    distanceKm: 140,
    difficulty: "进阶",
    category: "登山",
    region: "北京密云 / 河北兴隆",
    season: "6-9月",
    tags: ["避暑", "森林", "两日游", "徒步"],
    coverKey: "wulingPeak",
    galleryKeys: galleryKeysFor("R18"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day2(),
    highlights: [
      "雾灵山主峰在河北兴隆，北京密云亦可进入，有「三里不同天，一山有三季」之说",
      "盛夏避暑效果显著，林海和云雾是主景观",
      "可乘缆车减负，再徒步接近山顶",
      "第二天雾灵湖或云岫谷放松，避免两天都高强度",
      "山区天气变化快，领队有权调整登顶计划",
      "住山脚度假村，山顶务必备保暖层",
    ],
    description:
      "雾灵山是燕山主峰之一，主峰在河北兴隆，密云侧也能进山。垂直高差大，民间说「三里不同天，一山有三季」：山下夏天，山上可能还要外套。林海、云雾和秋季红叶是它和坝上草原完全不同的凉岛气质。\n\n两日安排一天登山看林海，一天湖区或谷地轻松游。不把两天都排成登顶。缆车视开放和排队情况使用。",
    itinerary: [
      { time: "D1 07:00", title: "赴雾灵山", detail: "登山或小交通+徒步，可乘缆车。住山脚度假村。" },
      { time: "D2 08:30", title: "雾灵湖或云岫谷", detail: "亲水或谷地轻松游，下午返京。" },
    ],
    feeInclude: "车费、1 晚住宿含早、门票、领队、责任险。",
    feeExclude: "缆车小交通、正餐、温泉。",
    equipment: "保暖层（山顶凉）、登山鞋、雨具。",
    notices: "山区天气变化快，领队有权调整登顶计划。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R19",
    title: "双龙峡 + 爨底下古村",
    subtitle: "京西峡谷与明清山村",
    days: 2,
    distanceKm: 100,
    difficulty: "休闲",
    category: "文化",
    region: "北京门头沟",
    season: "4-11月",
    tags: ["古村", "峡谷", "两日游", "摄影"],
    coverKey: "cuandi1",
    galleryKeys: galleryKeysFor("R19"),
    minGroupSize: 10,
    buses: ["coaster10", "bus30"],
    priceTiers: day2(),
    highlights: [
      "爨底下是门头沟斋堂镇明清山地四合院村落，保存较完整",
      "村巷、碉楼视角和灰瓦叠落是京西古道上的经典机位",
      "双龙峡在清水河河谷，夏季溪谷清凉，与百花山山系相连",
      "夜宿古村，可拍星空和灯火，听晋商与京西煤道故事",
      "古村保护建筑请勿攀爬；周末车位紧张，包车优势明显",
      "适合摄影和人文向游客",
    ],
    description:
      "爨底下村在门头沟斋堂，是北京保存较好的明清山地四合院聚落，灰瓦、高墙、依山叠院，和皖南古村不是同一套形制，但同样适合慢走和拍照。历史上它处在京西古道网络里，煤、货、人从门头沟进出京城。\n\n双龙峡在清水河谷，夏季有水、有林，和爨底下组成「一天峡谷、一晚古村」。第一天走峡，傍晚入住村内或邻近客栈；第二天早起拍晨雾村巷后返城。",
    itinerary: [
      { time: "D1 07:30", title: "双龙峡", detail: "清水河谷徒步，注意湿滑，夏季可亲水。" },
      { time: "D1 16:00", title: "入住爨底下", detail: "夜拍村巷，领队讲京西古道与山地四合院。" },
      { time: "D2 08:00", title: "古村深度游", detail: "四合院、碉楼视角，午饭后返京。" },
    ],
    feeInclude: "车费、1 晚客栈含早、门票、领队、责任险。",
    feeExclude: "正餐、摄影器材租赁。",
    equipment: "相机、舒适鞋、夜间防寒。",
    notices: "古村保护建筑请勿攀爬损坏；周末车位紧张，包车优势明显。",
    meetupPoints: [MEETUPS[1], MEETUPS[3]],
  },
  {
    code: "R20",
    title: "金山岭长城星空露营",
    subtitle: "最美长城之一 · 夜宿城下",
    days: 2,
    distanceKm: 140,
    difficulty: "进阶",
    category: "长城",
    region: "河北滦平 / 北京密云",
    season: "4-10月",
    tags: ["露营", "长城", "星空", "摄影"],
    coverKey: "jinshan",
    galleryKeys: galleryKeysFor("R20"),
    minGroupSize: 8,
    buses: ["coaster10", "bus30"],
    priceTiers: day2(),
    highlights: [
      "金山岭在河北滦平/北京密云交界，敌楼密集、野趣和视野都好，摄影里常被称作教材段落",
      "指定营地夜宿城下，看城墙剪影和星空（天气允许）",
      "比司马台更山野，比箭扣未开放段更可控",
      "第一天下午登城拍日落，夜间观星，第二天可选日出",
      "含帐篷或营位（见排期），禁火期无篝火",
      "不组织未开放野长城穿越；大风降温可能改为民宿",
    ],
    description:
      "金山岭长城横在河北滦平与北京密云之间，敌楼密度高、墙体有修复也有残段，远看层次清楚，是很多长城照片的「标准答案」来源地之一。它比八达岭野，比箭扣正规开放，适合有步行能力、又接受露营条件的小团。\n\n两日把登城和夜宿拆开：第一天下午上城拍日落，下撤到指定营地；夜间观星（云量够才看得到银河）。第二天早拍后返京。必须听从领队夜巡，林区禁火规定一票否决篝火。",
    itinerary: [
      { time: "D1 08:00", title: "赴金山岭", detail: "下午登城至日落，下撤指定营地，不走未开放段落。" },
      { time: "D1 20:00", title: "观星（视天气）", detail: "遵守林区和景区规定；禁火期无篝火。" },
      { time: "D2 05:30", title: "可选日出", detail: "早餐后返京，午后抵达。" },
    ],
    feeInclude: "车费、营位/帐篷（双人）、门票、领队、责任险。",
    feeExclude: "睡袋升级、餐饮（含简易早餐）、缆车。",
    equipment: "睡袋（季节匹配）、头灯、防潮垫、保暖衣、充电宝。",
    notices: "禁火期无篝火；大风降温可能改为民宿；必须听从领队夜巡安排。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R21",
    title: "涞源白石山峰林云海",
    subtitle: "世界地质公园 · 北方峰林",
    days: 2,
    distanceKm: 200,
    difficulty: "休闲",
    category: "山水",
    region: "河北保定涞源",
    season: "5-10月",
    tags: ["云海", "峰林", "两日游", "地质"],
    coverKey: "taihang1",
    galleryKeys: galleryKeysFor("R21"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day2(),
    highlights: [
      "涞源白石山为世界地质公园，大理岩峰林是华北少见的柱状山景",
      "云海不能保证，但住山脚争取第二天一早上行，遇到就值回票价",
      "索道解决大部分高差，老人小孩可同行",
      "山上可见白石山长城残段，和峰林同框",
      "适合摄影团；索道旺季排队请配合",
      "D1 抵达可温泉（自理），D2 栈道+索道后返京",
    ],
    description:
      "白石山在河北涞源，属于太行山北段，山体是大理岩峰林，和桂林喀斯特、张家界砂岩不是同一套石头，但远看同样是「峰从地上立起来」。它是京西南 2 日游里最有名的云海彩票：去了不一定遇得到，住在山脚是为了第二天赶早上山。\n\n索道把体力门槛降下来，栈道在峰丛间穿。图库为太行峰林与白石山长城实拍。云海、日照无法承诺。",
    itinerary: [
      { time: "D1 07:00", title: "赴涞源", detail: "车程较长。下午可先走部分步道或温泉（自理），入住山脚。" },
      { time: "D2 06:00", title: "白石山等云海", detail: "索道+栈道看峰林，午后返京，晚间到城。" },
    ],
    feeInclude: "车费、1 晚酒店含早、门票、领队、责任险。",
    feeExclude: "索道（常为必选项，部分排期含）、正餐。",
    equipment: "防风保暖、相机三脚架（可选）、防晒。",
    notices: "云海不能保证；索道排队较长请配合。",
    meetupPoints: [MEETUPS[3], MEETUPS[1]],
  },
  {
    code: "R22",
    title: "承德避暑山庄 + 外八庙",
    subtitle: "清代皇家夏都 · 世界遗产",
    days: 2,
    distanceKm: 230,
    difficulty: "休闲",
    category: "文化",
    region: "河北承德",
    season: "4-10月",
    tags: ["世界遗产", "皇家", "文化", "亲子"],
    coverKey: "chengdeResort",
    galleryKeys: galleryKeysFor("R22"),
    minGroupSize: 15,
    buses: ["bus30", "bus50"],
    priceTiers: day2(),
    highlights: [
      "承德避暑山庄是中国现存最大的古代皇家园林，世界遗产",
      "湖区、平原区、山区一天走不完，我们抓湖区精华加一段山区",
      "外八庙重点看普宁寺大乘之阁、普陀宗乘之庙等 1-2 座，避免寺庙疲劳",
      "讲解清帝北巡、木兰秋狝与多民族治理，不是只拍宫殿",
      "适合家庭和单位参观学习；山庄面积大请不要掉队",
      "部分殿宇、电瓶车需另购，以排期套票为准",
    ],
    description:
      "承德避暑山庄是清帝夏天处理政务和居住的园子，面积远大于北京多数公园，湖区有金山亭、热河泉一带的水面，山区有永佑寺舍利塔等轮廓。它不是故宫：故宫是紫禁城的宫殿群，山庄是塞外的皇家园林，把江南理水和塞外山岗放在同一个围墙里。\n\n外八庙环列山庄之外，普宁寺大乘之阁、普陀宗乘之庙（仿布达拉宫形制）是最常看的两座。本线路第一天山庄，第二天寺庙，避免一天塞满。封面与图库均为山庄和外八庙实拍，不再使用故宫太和殿照片。",
    itinerary: [
      { time: "D1 07:00", title: "赴承德", detail: "京承方向约 3 小时。下午游避暑山庄湖区及选定山区，入住承德市区。" },
      { time: "D2 08:30", title: "外八庙", detail: "普宁寺等 1-2 座重点，下午返京约 20:00 到。" },
    ],
    feeInclude: "车费、住宿含早、山庄及指定寺庙门票、导游、责任险。",
    feeExclude: "正餐、电瓶车、未含寺庙。",
    equipment: "舒适鞋（山庄很大）、防晒、证件。",
    notices: "山庄面积大，请不要掉队；部分殿宇需另购票。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R23",
    title: "蓟州盘山 + 黄崖关长城",
    subtitle: "京东第一山 · 蓟北雄关",
    days: 2,
    distanceKm: 130,
    difficulty: "休闲",
    category: "长城",
    region: "天津蓟州",
    season: "4-11月",
    tags: ["两日游", "登山", "长城", "天津"],
    coverKey: "panshan",
    galleryKeys: galleryKeysFor("R23"),
    minGroupSize: 12,
    buses: ["bus30", "bus50"],
    priceTiers: day2(),
    highlights: [
      "天津蓟州盘山有「京东第一山」之称，松石、飞泉、寺院叠在一起",
      "黄崖关长城在蓟北，关城有八卦城等独特格局，和八达岭观感不同",
      "出京向东，周日返程相对顺；可尝蓟州津味",
      "两日拆开：一天盘山观光，一天黄崖关登城，不住赶场",
      "盘山索道旺季排队，请预留耐心",
      "适合想换一条「不是又去怀柔」的长城周末",
    ],
    description:
      "盘山在天津蓟州，山势近城，松石和泉水是传统卖点，有「京东第一山」的老名声。黄崖关在蓟县北部，长城在这里收成关城，还有八卦城一类的布局，和北京境内常见的山脊墙不一样。\n\n两日把山和关拆开，住蓟州城区或山脚，第二天不赶场。图库为盘山与黄崖关实拍。",
    itinerary: [
      { time: "D1 07:30", title: "盘山", detail: "索道+步道看松石飞泉，住蓟州。" },
      { time: "D2 08:30", title: "黄崖关长城", detail: "关城与城墙，午后返京。" },
    ],
    feeInclude: "车费、1 晚含早、门票、领队、责任险。",
    feeExclude: "索道、正餐。",
    equipment: "运动鞋、防晒。",
    notices: "盘山索道旺季排队，请预留耐心。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R24",
    title: "乌兰布统坝上草原",
    subtitle: "坝上小呼伦贝尔 · 日出与骑旅",
    days: 3,
    distanceKm: 420,
    difficulty: "休闲",
    category: "草原",
    region: "内蒙古赤峰 / 河北围场",
    season: "6-9月",
    tags: ["草原", "三日游", "骑马", "摄影"],
    coverKey: "ulanbutong",
    galleryKeys: galleryKeysFor("R24"),
    minGroupSize: 20,
    buses: ["bus30", "bus50"],
    priceTiers: day3(),
    highlights: [
      "乌兰布统在内蒙古克什克腾旗，是京北最知名的坝上草原摄影地",
      "可安排日出、桦木沟、将军泡子、蛤蟆坝等机位（视天气和管制）",
      "含短时正规马队骑乘（时长见排期），不进购物店",
      "住木屋或度假村，适合家庭；晨间很凉请备保暖层",
      "草原紫外线强，勿践踏牧民草场",
      "三天两晚把车程摊开，避免一天刷完所有点",
    ],
    description:
      "乌兰布统草原在内蒙古赤峰克什克腾旗，和河北围场、丰宁同属坝上，但镜头里更「草」：缓丘、桦树、泡子，电影《还珠格格》等取景让这里出了名。它不是呼伦贝尔那样的无边平坦，而是有地形起伏的草甸，所以日出和侧光特别好看。\n\n三天两晚：D1 进坝上看夕阳，D2 核心机位和骑马，D3 日出后返京。骑马只走正规马队。图库为乌兰布统及同属坝上的塞罕坝、丰宁草甸实拍，不再用欧美牧场图充数。",
    itinerary: [
      { time: "D1 06:30", title: "出京进坝上", detail: "车程长。傍晚将军泡子或蛤蟆坝取景，入住度假村。" },
      { time: "D2 全天", title: "草原深度", detail: "桦木沟、短时骑乘、可选射箭（自理）。紫外线强请防晒。" },
      { time: "D3 04:30", title: "日出后返京", detail: "预计晚间抵京。" },
    ],
    feeInclude: "往返车、2 晚住宿含早、指定景点、骑马体验（短时）、领队、责任险。",
    feeExclude: "正餐、加时骑马、滑沙等自费、单房差。",
    equipment: "防晒、墨镜、防风外套、长裤（骑马）、保暖层（晨间很凉）。",
    notices: "草原紫外线强；骑马须听从马夫，儿童需家长陪同；勿践踏牧民草场。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R25",
    title: "木兰围场皇家猎苑",
    subtitle: "塞外林海 · 清帝秋狝之地",
    days: 3,
    distanceKm: 400,
    difficulty: "休闲",
    category: "草原",
    region: "河北承德围场",
    season: "6-10月",
    tags: ["三日游", "森林", "草原", "文化"],
    coverKey: "saihanba",
    galleryKeys: galleryKeysFor("R25"),
    minGroupSize: 16,
    buses: ["bus30", "bus50"],
    priceTiers: day3(),
    highlights: [
      "木兰围场是清代皇家猎苑，秋狝之地，林海与草甸交织",
      "塞罕坝机械林场把沙地变成林海，是生态教育现场",
      "同样是坝上，这里更「林」，乌兰布统更「草」",
      "秋季色彩极佳；林区严禁烟火",
      "适合单位团建和亲子自然教育",
      "海拔与温差大，夏天早晚也要备衣",
    ],
    description:
      "木兰围场在河北承德围场县，清帝秋狝在这里举行，今天看到的是林场、草甸和博物馆叠在一起的坝上。塞罕坝机械林场是其中最广为人知的一块：几代人把沙地变成林海，七星湖、林海观光是常见停点。\n\n和乌兰布统相比，这条线更偏森林和生态讲解，而不是纯摄影机位。三天含塞罕坝亮点和围场停留，可顺路承德但不超时。",
    itinerary: [
      { time: "D1", title: "进围场", detail: "承德方向，傍晚林区漫步，入住围场或塞罕坝周边。" },
      { time: "D2", title: "塞罕坝与围场核心", detail: "林海、七星湖、博物馆视开放。严禁烟火。" },
      { time: "D3", title: "返京", detail: "可顺路承德稍作停留（不超时）。" },
    ],
    feeInclude: "车费、2 晚含早、门票套餐、领队、责任险。",
    feeExclude: "正餐、景区小交通、演艺。",
    equipment: "防寒（即使夏天早晚也凉）、舒适鞋、雨衣。",
    notices: "林区严禁烟火；海拔与温差请老人小孩备衣。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R26",
    title: "野三坡深度 + 十渡漂流",
    subtitle: "百里峡·百草畔·拒马河 三日慢游",
    days: 3,
    distanceKm: 160,
    difficulty: "休闲",
    category: "山水",
    region: "河北涞水 / 北京房山",
    season: "5-10月",
    tags: ["三日游", "峡谷", "漂流", "亲子"],
    coverKey: "yesanpo",
    galleryKeys: galleryKeysFor("R26"),
    minGroupSize: 15,
    buses: ["bus30", "bus50"],
    priceTiers: day3(),
    highlights: [
      "三日把野三坡走深：百里峡 + 百草畔 + 十渡拒马河",
      "百里峡蝎子沟看峡谷，百草畔看亚高山草甸和云海（看天气）",
      "百草畔与百花山同属京西高海拔草甸带，图库用百花山草甸实拍对照",
      "最后一天十渡漂流或峰林，返京不留遗憾",
      "住宿固定一地，减少搬运行李，比两日线从容",
      "适合不想赶路的家庭和团队",
    ],
    description:
      "野三坡不止一条峡谷。三日线把百里峡、百草畔和房山十渡摊开：D1 走蝎子沟核心段，D2 上百草畔看草甸云海（索道减负），D3 到拒马河对岸十渡玩水再返城。住宿固定在野三坡，少搬一次行李。\n\n百草畔和门头沟百花山同属这一带的亚高山草甸，图库用百花山草甸、十渡拒马河与野三坡实拍，不再用美国峡谷图。",
    itinerary: [
      { time: "D1", title: "百里峡", detail: "蝎子沟核心段，住野三坡。" },
      { time: "D2", title: "百草畔", detail: "索道+草甸，晚间自由。云海看天气。" },
      { time: "D3", title: "十渡漂流", detail: "拒马河玩水或峰林观光后返京。" },
    ],
    feeInclude: "车费、2 晚含早、核心门票、领队、责任险。",
    feeExclude: "索道、漂流（部分排期含）、正餐。",
    equipment: "防晒、速干、替换衣物。",
    notices: "三日仍属短途，行李请精简。",
    meetupPoints: [MEETUPS[3], MEETUPS[1]],
  },
  {
    code: "R27",
    title: "秦皇岛北戴河 · 山海关",
    subtitle: "海与关 · 京津冀海岸线",
    days: 3,
    distanceKm: 300,
    difficulty: "休闲",
    category: "海滨",
    region: "河北秦皇岛",
    season: "6-9月",
    tags: ["海滨", "三日游", "亲子", "长城"],
    coverKey: "beidaihe",
    galleryKeys: galleryKeysFor("R27"),
    minGroupSize: 20,
    buses: ["bus30", "bus50"],
    priceTiers: day3(),
    highlights: [
      "山海关「天下第一关」，是明长城东端最著名的关城之一",
      "老龙头长城入海，城砖直接顶到渤海",
      "北戴河/黄金海岸游泳、骑行、沙滩，必须在救生旗水域",
      "D3 可看鸽子窝日出（可选），不进商业洗脑店",
      "适合暑期家庭；海鲜餐和海上项目自理",
      "日光强烈请反复补涂防晒",
    ],
    description:
      "山海关在河北秦皇岛，关城「天下第一关」匾额那一侧是城，老龙头则把长城砌进海里，和北京山脊上的边墙完全不是一种结尾。北戴河是京津冀最经典的避暑海岸，沙岸、林荫路和鸽子窝（鹰角石）日出是老记忆，不是热带椰林沙滩。\n\n三日：D1 关城+老龙头，D2 海边全天，D3 鸽子窝或沿海外观后返京。图库为北戴河全景、山海关与老龙头实拍，不再用东南亚海滩图。",
    itinerary: [
      { time: "D1", title: "山海关·老龙头", detail: "关城、天下第一关、老龙头入海石城。入住北戴河或秦皇岛。" },
      { time: "D2", title: "海滨休闲", detail: "北戴河游泳、骑行、沙滩，只在救生旗水域下水。" },
      { time: "D3", title: "鸽子窝日出（可选）后返", detail: "下午抵京。" },
    ],
    feeInclude: "车费、2 晚含早、关城及指定景点、领队、责任险。",
    feeExclude: "海鲜餐、海上项目、自行车升级。",
    equipment: "泳衣、防晒、拖鞋、风衣。",
    notices: "游泳必须在救生水域；日光强烈请补涂防晒。",
    meetupPoints: [MEETUPS[0], MEETUPS[2]],
  },
  {
    code: "R28",
    title: "坝上草原 + 承德皇家行宫",
    subtitle: "草原星空与山庄园林的五日组合",
    days: 5,
    distanceKm: 650,
    difficulty: "休闲",
    category: "草原",
    region: "内蒙古 / 河北承德",
    season: "6-9月",
    tags: ["五日游", "草原", "世界遗产", "深度"],
    coverKey: "ulanbutong",
    galleryKeys: galleryKeysFor("R28"),
    minGroupSize: 20,
    buses: ["bus30", "bus50"],
    priceTiers: day5(),
    highlights: [
      "乌兰布统或围场深度约 3 天，再接承德避暑山庄与外八庙 2 天",
      "坝上拍日出草甸，承德走皇家园林，一条线两种尺度",
      "不挤在周末两天，适合年假和调休长周末",
      "纯玩无强制消费；天气可能调整机位顺序",
      "请预留 1 天缓冲再安排周一重要会议",
      "图库为坝上实拍+山庄寺庙实拍，不用故宫照片冒充外八庙",
    ],
    description:
      "五日把坝上自然和承德皇家园林连成闭环：前面在乌兰布统或塞罕坝看草、林、日出，中间留一天转移，后面两天走避暑山庄湖区和外八庙。这样既不会只看草原，也不会只看寺庙。\n\n山庄是塞外皇家园林，外八庙是环列的藏传佛教寺庙群，和北京故宫不是同一处。节奏按「两天摄影+一天过渡+两天文化」设计。",
    itinerary: [
      { time: "D1", title: "进坝上", detail: "夕阳机位，住草原度假村。" },
      { time: "D2", title: "草原核心", detail: "骑马、桦木沟、泡子或林海，视走乌兰布统还是围场。" },
      { time: "D3", title: "林海或转移承德", detail: "过渡日，减少疲劳。" },
      { time: "D4", title: "避暑山庄", detail: "湖区+山区精华。" },
      { time: "D5", title: "外八庙后返京", detail: "普宁寺等，晚间到京。" },
    ],
    feeInclude: "全程车、4 晚住宿含早、景点套票、领队导游、责任险。",
    feeExclude: "正餐、单房差、自费体验。",
    equipment: "分层穿衣、防晒、药品、身份证。",
    notices: "五日行程仍可能因天气调整机位顺序；请预留 1 天缓冲再安排周一重要会议。",
    meetupPoints: [MEETUPS[0]],
  },
  {
    code: "R29",
    title: "五台山朝圣 + 大同云冈",
    subtitle: "清凉佛国与皇家石窟",
    days: 5,
    distanceKm: 900,
    difficulty: "休闲",
    category: "文化",
    region: "山西忻州 / 大同",
    season: "5-10月",
    tags: ["五日游", "佛教", "石窟", "世界遗产"],
    coverKey: "wutai",
    galleryKeys: galleryKeysFor("R29"),
    minGroupSize: 20,
    buses: ["bus30", "bus50"],
    priceTiers: day5(),
    highlights: [
      "五台山是文殊菩萨道场，四大佛教名山之首，台怀镇集中了塔院寺、菩萨顶等",
      "云冈石窟在大同，北魏皇家开凿，和龙门、敦煌并称",
      "悬空寺在浑源，木构贴在翠屏山悬崖上，常作为返程加站",
      "五日仍从北京往返，不安排赶庙，尊重宗教场所礼仪",
      "台怀海拔偏高，早晚凉；寺庙内请勿短裙喧哗",
      "图库为五台山佛塔、云冈石窟与悬空寺实拍",
    ],
    description:
      "五台山在山西忻州，是文殊菩萨道场，台怀盆地里塔院寺白塔、菩萨顶等构成「清凉佛国」的核心印象。云冈石窟在大同西郊，石窟开在砂岩崖壁上，佛像尺度和北魏皇家工程是另一套看点。悬空寺在浑源恒山脚下，楼阁用梁柱插进悬崖，远看像贴在垂直岩面上。\n\n五日：D1-D3 五台山，D4 云冈，D5 悬空寺或华严寺后返京。不赶庙、不强制随喜。",
    itinerary: [
      { time: "D1", title: "赴五台山", detail: "车程长，入住台怀，晚间自由适应海拔和温差。" },
      { time: "D2-D3", title: "台怀核心寺庙", detail: "菩萨顶、塔院寺等，不安排赶庙，素食居多。" },
      { time: "D4", title: "云冈石窟", detail: "重点窟参观，住大同。" },
      { time: "D5", title: "悬空寺后返京", detail: "浑源悬空寺或大同华严寺，抵达较晚。" },
    ],
    feeInclude: "车费、4 晚含早、核心门票、导游、责任险。",
    feeExclude: "香火随喜、索道、正餐、未含景点。",
    equipment: "素净服装、舒适鞋、防晒、高原早晚外套（台怀偏凉）。",
    notices: "寺庙内请勿喧哗短裙；素食餐厅居多；进寺安检请配合。",
    meetupPoints: [MEETUPS[1], MEETUPS[0]],
  },
  {
    code: "R30",
    title: "张家口草原天路 + 崇礼",
    subtitle: "天路牧歌 · 冬奥雪乡的夏日",
    days: 5,
    distanceKm: 480,
    difficulty: "休闲",
    category: "草原",
    region: "河北张家口",
    season: "6-10月",
    tags: ["五日游", "天路", "草原", "冬奥"],
    coverKey: "zhangbeiSkyline",
    galleryKeys: galleryKeysFor("R30"),
    minGroupSize: 16,
    buses: ["bus30", "bus50"],
    priceTiers: day5(),
    highlights: [
      "张北草原天路是华北最知名的景观公路之一，分段走而不是一天刷完",
      "张北 Grass Skyline 等观景平台可看坝上天际线和风车",
      "崇礼夏秋金林、冬日可改为万龙等雪场主题排期",
      "桦皮岭云海看运气；天路可能管制和收费",
      "切勿下车在公路上拍照挡道",
      "适合想坐大巴走天路、又不必自己开车的人",
    ],
    description:
      "草原天路在张家口张北、万全一带的坝上，是一条沿着山脊修的景观公路，风车、草坡和远山是主画面，不是内蒙古腹地的无人区。崇礼是冬奥雪场集群，夏天是避暑和金秋，冬天才是万龙等雪道。\n\n五日把张北、天路和崇礼摊开：分段停留、轻徒步，而不是一天开完一百多公里。冬季排期可切滑雪，需另配装备说明。图库为张北天路观景、崇礼金秋与万龙雪场实拍。",
    itinerary: [
      { time: "D1", title: "进张北", detail: "草原度假村入住，傍晚看坝上天际线。" },
      { time: "D2", title: "天路东段", detail: "观景台、风车、日落。禁止下车占道拍照。" },
      { time: "D3", title: "天路西段或沽源", detail: "视天气和交通管制。" },
      { time: "D4", title: "崇礼", detail: "夏秋徒步/缆车看金林，冬日滑雪主题。" },
      { time: "D5", title: "返京", detail: "经京藏或京礼。" },
    ],
    feeInclude: "车费、4 晚含早、部分景区、领队、责任险。",
    feeExclude: "天路沿线餐饮、滑雪装备、缆车加项。",
    equipment: "防风、防晒、晕车药（山路）、冬季雪具。",
    notices: "天路可能交通管制和收费，以现场为准；切勿下车在公路上拍照挡道。",
    meetupPoints: [MEETUPS[1], MEETUPS[0]],
  },
];

module.exports = { ROUTES, PHOTO, PHOTO_FALLBACK, MEETUPS, galleryKeysFor };
